graph TD

subgraph VPC [Virtual_Private_Cloud]
subgraph region [us-east-1 Region]
subgraph Public Subnet
ALB@{ img: "https://api.iconify.design/logos/aws-elb.svg", label: "Application_LB + SG", pos: "b", w: 60, h: 60, constraint: "on" }
end

subgraph Private Subnet
ASG[Auto_scaling_Group]

  subgraph AZ1 [Availability Zone 1]
  EC21@{ img: "https://api.iconify.design/logos/aws-ec2.svg", label: "EC2+SG", pos: "b", w: 60, h: 60, constraint: "on" }
end

subgraph AZ2 [Availability Zone 2]
EC22@{ img: "https://api.iconify.design/logos/aws-ec2.svg", label: "EC2-1+SG", pos: "b", w: 60, h: 60, constraint: "on" }
  end
RDS@{ img: "https://api.iconify.design/logos/aws-rds.svg", label: "Relational_DB + EN", pos: "b", w: 60, h: 60, constraint: "on" }
DDB@{ img: "https://api.iconify.design/logos/aws-dynamodb.svg", label: "Dynamo_DB + EN", pos: "b", w: 60, h: 60, constraint: "on" }
end
end
end

CF@{ img: "https://api.iconify.design/logos/aws-cloudfront.svg", label: "CloudFront_CDN + WAF", pos: "b", w: 60, h: 60, constraint: "on" }
IGW[Internet_Gateway]
S3@{ img: "https://api.iconify.design/logos/aws-s3.svg", label: "S3_Bucket + EN", pos: "b", w: 60, h: 60, constraint: "on" }

CF --> ALB
ALB --> EC21
ALB --> EC22
EC21 --> DDB
EC22 --> DDB
CF --> S3
EC21 --> RDS
EC22 --> RDS
EC21 --> ASG
EC22 --> ASG
ALB --> IGW







    
